Feat: OAuth2.0 kakao, naver, google 기능을 위한 OAuth2User, service 구현체 생성
nsce9806q/k-spring-security pull request #9
Opened 2023-06-16 11:40 UTC by cspyo

### 한 줄 설명
OAuth2.0 [kakao, naver, google] 기능을 위한 OAuth2User, service 구현체 생성

### 상세 설명
- Provider 별 Attribute parsing 을 통한 `UserInfo` 클래스 생성
- 사용자가 정의할 멤버 도메인 모델이 주입된 `KauthUserPrincipal` 추상 클래스 생성
- 사용자 Repository와 연결된 멤버 관련 로직을 작성할 `KOAuthUserService` 추상 클래스 생성
    - 사용자는 `processMemberByOAuthUserInfo` 메소드를 구현하면 된다

### 관련 이슈
이슈: #7

2023-06-16 12:52 UTC, nsce9806q commented on src/main/java/org/swmaestro/kauth/oauth/entity/KauthUserPrincipal.java
> +    private M member;
member라는 변수명의 의도는 알고있지만,
클래스와 구현하고 있는 인터페이스의 이름이 User라서 Member 대신 User로 하면 일관성 측면에서 좋을거 같아요!

2023-06-16 12:52 UTC, nsce9806q commented on src/main/java/org/swmaestro/kauth/oauth/info/OAuth2UserInfoFactory.java
> +    public static OAuth2UserInfo getOAuth2UserInfo(ProviderType providerType, Map<String, Object> attributes) {
static 메소드 대신  스프링 컨테이너에서 관리할 수 있도록 해당 클래스를 Bean으로 등록(Component 어노테이션)하면 어떨까요?? (이렇게 하면 KOAuth2UserService 상속 클래스에 해당 Bean을 DI 해야합니다)

2023-06-16 13:05 UTC, cspyo commented on src/main/java/org/swmaestro/kauth/oauth/entity/KauthUserPrincipal.java
> +    private M member;
사용자가 직접 구현하게 되는 부분이라 Spring 에서 주로 사용되는 유저 도메인 모델인 Member 를 연상할 수 있는 네이밍을 사용했습니다.
일관성보다 저희의 의도를 사용자가 알게끔 유도하고 구현에 방향성을 제시하는 쪽으로 집중했는데 어떨까요??

좋은 리뷰 감사합니다.  

+ final 키워드로 생성자 구현을 강제하는 것도 의도 파악에 도움이 될 것 같습니다.

2023-06-16 15:15 UTC, krapie requested changes

2023-06-16 15:15 UTC, krapie commented on src/main/java/org/swmaestro/kauth/oauth/info/OAuth2UserInfoFactory.java
> +}
POSIX 표준을 지켜야 해서, 여기 아래에 Newline(개행) 해 주셔야 할 것 같아요.

Reference:
- https://stackoverflow.com/questions/729692/why-should-text-files-end-with-a-newline
- https://blog.coderifleman.com/2015/04/04/text-files-end-with-a-newline/

2023-06-16 15:15 UTC, krapie commented on src/main/resources/application-oauth.yaml
> +            user-name-attribute: id
여기 아래도 마찬가지 입니다!

2023-06-17 01:00 UTC, cspyo commented on src/main/java/org/swmaestro/kauth/oauth/info/OAuth2UserInfoFactory.java
> +}
확인했습니다!
레퍼런스 링크 감사합니다.

2023-06-17 06:05 UTC, nsce9806q commented
LGTM

2023-06-17 06:05 UTC, merged

2023-06-17 06:07 UTC, nsce9806q commented
resolve #7